# BUILD - C++ event queue utilities

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "event_queue",
    hdrs = [
        "mpsc_queue.h",
        "ring_buffer.h",
    ],
    copts = ["-std=c++20"],
)

cc_library(
    name = "event_queue_headers",
    hdrs = [
        "mpsc_queue.h",
        "ring_buffer.h",
    ],
    copts = ["-std=c++20"],
)
